import os
from googleapiclient.discovery import build
from google_auth_oauthlib import flow
import googleapiclient.errors
import webbrowser
import json

scopes = ["https://www.googleapis.com/auth/youtube.force-ssl"]

os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

service_name = 'youtube'
service_version = 'v3'
secrets = "Youtube_Client_Secret.json"

flow = flow.InstalledAppFlow.from_client_secrets_file(client_secrets_file=secrets, scopes=scopes)
credentials = flow.run_console()

youtube = build(service_name, service_version, credentials=credentials)
request = youtube.playlists().insert(
    part="snippet",
    body={
        "snippet":{
            "title":"Autogenerated Playlist",
            "description":"Generated using a python script."
        }
    }
)
response = request.execute()
id = response['id']
url = 'https://www.youtube.com/playlist?list=' + id
print(json.dumps(response, sort_keys=True, indent=4))
webbrowser.open_new_tab(url)
